### ISSUE TITLE
The server is breaking down

### ISSUE THREAD

**Issue by egorkAh** [hypervortex/VH-Bombsquad-Modded-Server-Files#3]
how do I disable the blocking of new accounts? if a new account logs into the server, the server simply breaks down

**Comment by D2-Rohan-84013** [comment]
https://github.com/hypervortex/VH-Bombsquad-Modded-Server-Files/blob/1885240c1c742d3af9e9b271ad6e2221ed1c94cb/dist/ba_root/mods/setting.json#L313

just reduce time req to join and chat
