### ISSUE TITLE
constant errors on a clean server , I didn't change anything

### ISSUE THREAD

**Issue by egorkAh** [hypervortex/VH-Bombsquad-Modded-Server-Files#5]
![image](https://github.com/user-attachments/assets/d6e27279-98b8-4086-901c-7688717f5eba)

**Comment by egorkAh** [comment]
![image](https://github.com/user-attachments/assets/5ebd2a02-af0d-48bc-b84c-3c85d822bf7e)

**Comment by egorkAh** [comment]
![image](https://github.com/user-attachments/assets/9619d3eb-dfcf-4b21-bd7e-d241702cc8a0)

**Comment by hypervortex** [comment]
are u having any problem cause of these erros ?

**Comment by egorkAh** [comment]
it affects the game performance

**Comment by hypervortex** [comment]
Will fix it soon Sorry for the inconvenience

**Comment by hypervortex** [comment]
Will fix it soon Sorry for the inconvenience
